
// This file was auto-generated by ML.NET Model Builder. 

using CancerDiagonosticsMLModel2_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
CancerDiagonosticsMLModel2.ModelInput sampleData = new CancerDiagonosticsMLModel2.ModelInput()
{
    GENDER = @"M",
    AGE = 74F,
    SMOKING = 2F,
    YELLOW_FINGERS = 1F,
    ANXIETY = 1F,
    PEER_PRESSURE = 1F,
    CHRONIC_DISEASE = 2F,
    FATIGUE = 2F,
    ALLERGY = 2F,
    WHEEZING = 1F,
    ALCOHOL_CONSUMING = 1F,
    COUGHING = 1F,
    SHORTNESS_OF_BREATH = 2F,
    SWALLOWING_DIFFICULTY = 2F,
    CHEST_PAIN = 2F,
};



Console.WriteLine("Using model to make single prediction -- Comparing actual LUNG_CANCER with predicted LUNG_CANCER from sample data...\n\n");


Console.WriteLine($"GENDER: {@"M"}");
Console.WriteLine($"AGE: {74F}");
Console.WriteLine($"SMOKING: {2F}");
Console.WriteLine($"YELLOW_FINGERS: {1F}");
Console.WriteLine($"ANXIETY: {1F}");
Console.WriteLine($"PEER_PRESSURE: {1F}");
Console.WriteLine($"CHRONIC_DISEASE: {2F}");
Console.WriteLine($"FATIGUE: {2F}");
Console.WriteLine($"ALLERGY: {2F}");
Console.WriteLine($"WHEEZING: {1F}");
Console.WriteLine($"ALCOHOL_CONSUMING: {1F}");
Console.WriteLine($"COUGHING: {1F}");
Console.WriteLine($"SHORTNESS_OF_BREATH: {2F}");
Console.WriteLine($"SWALLOWING_DIFFICULTY: {2F}");
Console.WriteLine($"CHEST_PAIN: {2F}");


var predictionResult = CancerDiagonosticsMLModel2.Predict(sampleData);
Console.WriteLine($"\n\nPredicted Sentiment: {predictionResult.PredictedLabel}\n\n");

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

